SELECT * FROM TAB;

--NVL
select first_name,last_name,nvl(first_name,last_name) from employees where employee_id in (100,101);

--INTSTR  
SELECT * FROM DUAL; --PLACE HOLDER FOR TABLE
--INSTR(STRING/COLUMN,SUBSTRING,WHERE TO START,WHICH OCCURENCE YOU WANT);
SELECT INSTR('ABCDECECRC','C',2,3) FROM DUAL;


--SUBSTR
 SELECT SUBSTR('AADFVBEBE',3,4) FROM DUAL;
 
--TO_CHAR
SELECT TO_CHAR(SALARY),SALARY FROM emp ;

--CEIL
SELECT CEIL(-17.36) FROM dual;

--FLOOR
SELECT FLOOR(25.75) FROM DUAL;

--POWER
SELECT POWER(4, 2) FROM DUAL;

--ROUND
SELECT ROUND(235.415, 1) FROM DUAL;

--REPLACE
SELECT REPLACE('SQL Mutorial', 'M', 'T') FROM DUAL;

--MOD
SELECT MOD(18, 4) FROM DUAL;


--MIN,MAX,AVG
SELECT MIN(SAL),MAX(SAL),AVG(SAL) FROM EMP;

--COUNT,SUM
--SELECT COUNT(column_name) FROM table_name WHERE condition;
--SELECT SUM(column_name) FROM table_name WHERE condition;




